### ISSUE TITLE
Add documentation for setting S3-Path

### ISSUE THREAD

**Issue by Brice187** [sergeyshevch/s3manager-helm#3]
Currently you have to guess how to setup the s3 destination (e.g. add **env**)

**Comment by dsputnikk** [comment]
> Currently you have to guess how to setup the s3 destination (e.g. add **env**)

@Brice187 Any chance you could post your solution? I assume we want pointers in ConfigMap and secret key in Secrets, fed in as env's.

**Comment by Brice187** [comment]
As this project seems to be abandoned, I go with the yamls bei cloudlena:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3manager
  template:
    metadata:
      labels:
        app: s3manager
    spec:
      serviceAccountName: s3manager
      containers:
        - name: s3manager
          image: example.com/dockerhub/cloudlena/s3manager:v0.5.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #resources:
          #  {}
          env:
          - name: "ENDPOINT"
            value: "storage.example.com"
          - name: "SKIP_SSL_VERIFICATION"
            value: "true"
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: accesskey
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: secretkey
```

**Comment by dsputnikk** [comment]
> As this project seems to be abandoned, I go with the yamls bei cloudlena:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: s3manager
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: s3manager
>   template:
>     metadata:
>       labels:
>         app: s3manager
>     spec:
>       serviceAccountName: s3manager
>       containers:
>         - name: s3manager
>           image: example.com/dockerhub/cloudlena/s3manager:v0.5.0"
>           imagePullPolicy: IfNotPresent
>           ports:
>             - name: http
>               containerPort: 8080
>               protocol: TCP
>           #resources:
>           #  {}
>           env:
>           - name: "ENDPOINT"
>             value: "storage.example.com"
>           - name: "SKIP_SSL_VERIFICATION"
>             value: "true"
>           - name: ACCESS_KEY_ID
>             valueFrom:
>               secretKeyRef:
>                 name: s3-credentials
>                 key: accesskey
>           - name: SECRET_ACCESS_KEY
>             valueFrom:
>               secretKeyRef:
>                 name: s3-credentials
>                 key: secretkey
> ```

Thanks, that's helpful. Unfortunately, I really want a helm method so I can use my existing CI/CD tooling & helm would make that far easier.

**Comment by 6DammK9** [comment]
Visiting here because of connecting to ceph Object Storage ~~super duper complicated~~ (rook-ceph helm chart)
So far this chart used a custom image in [quay.io](https://quay.io/repository/sergeyshevch/s3manager?tab=tags&tag=feature_refactoring) instead of the official image in docker hub.

For the most helm-ish approach:

```sh
helm repo add sergeyshevch https://sergeyshevch.github.io/charts
helm install s3manager sergeyshevch/s3manager \
  --namespace s3manager-system --create-namespace \
  --set image.repository=cloudlena/s3manager \
  --set image.tag=latest
```

Edit the generated `ConfigMap` (I use Headlamp for k8s GUI):

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: s3manager
  namespace: s3manager-system
# Add this session.
data:
  PORT: '80'
  SKIP_SSL_VERIFICATION: 'true'
  USE_SSL: 'false'
  ENDPOINT: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local:80
  ACCESS_KEY_ID: secret_generated_from_objectbucketclaim
  SECRET_ACCESS_KEY: secret_generated_from_objectbucketclaim
```

Finally restart the Deployment. There is a `envFrom.configMapRef` in this helm chart to config the environment variables.
